#define LA(val) LINEA_##val
#define LINEA_mouse_cdb C_SYM(linea_vars)+54
#define LINEA_INQ_TAB C_SYM(linea_vars)+128
#define LINEA_DEV_TAB C_SYM(linea_vars)+218
#define LINEA_GCURX C_SYM(linea_vars)+308
#define LINEA_GCURY C_SYM(linea_vars)+310
#define LINEA_HIDE_CNT C_SYM(linea_vars)+312
#define LINEA_MOUSE_BT C_SYM(linea_vars)+314
#define LINEA_REQ_COL C_SYM(linea_vars)+316
#define LINEA_SIZ_TAB C_SYM(linea_vars)+412
#define LINEA_TERM_CH C_SYM(linea_vars)+442
#define LINEA_chc_mode C_SYM(linea_vars)+444
#define LINEA_CUR_WORK C_SYM(linea_vars)+446
#define LINEA_def_font C_SYM(linea_vars)+450
#define LINEA_font_ring C_SYM(linea_vars)+454
#define LINEA_font_count C_SYM(linea_vars)+470
#define LINEA_line_cw C_SYM(linea_vars)+472
#define LINEA_loc_mode C_SYM(linea_vars)+474
#define LINEA_num_qc_lines C_SYM(linea_vars)+556
#define LINEA_str_mode C_SYM(linea_vars)+558
#define LINEA_val_mode C_SYM(linea_vars)+560
#define LINEA_cur_ms_stat C_SYM(linea_vars)+562
#define LINEA_disab_cnt C_SYM(linea_vars)+564
#define LINEA_newx C_SYM(linea_vars)+566
#define LINEA_newy C_SYM(linea_vars)+568
#define LINEA_draw_flag C_SYM(linea_vars)+570
#define LINEA_mouse_flag C_SYM(linea_vars)+571
#define LINEA_sav_cur_x C_SYM(linea_vars)+572
#define LINEA_sav_cur_y C_SYM(linea_vars)+574
#define LINEA_retsav C_SYM(linea_vars)+576
#define LINEA_mouse_cursor_save C_SYM(linea_vars)+580
#define LINEA_tim_addr C_SYM(linea_vars)+844
#define LINEA_tim_chain C_SYM(linea_vars)+848
#define LINEA_user_but C_SYM(linea_vars)+852
#define LINEA_user_cur C_SYM(linea_vars)+856
#define LINEA_user_mot C_SYM(linea_vars)+860
#define LINEA_v_cel_ht C_SYM(linea_vars)+864
#define LINEA_v_cel_mx C_SYM(linea_vars)+866
#define LINEA_v_cel_my C_SYM(linea_vars)+868
#define LINEA_v_cel_wr C_SYM(linea_vars)+870
#define LINEA_v_col_bg C_SYM(linea_vars)+872
#define LINEA_v_col_fg C_SYM(linea_vars)+874
#define LINEA_v_cur_ad C_SYM(linea_vars)+876
#define LINEA_v_cur_of C_SYM(linea_vars)+880
#define LINEA_v_cur_cx C_SYM(linea_vars)+882
#define LINEA_v_cur_cy C_SYM(linea_vars)+884
#define LINEA_v_period C_SYM(linea_vars)+886
#define LINEA_v_cur_tim C_SYM(linea_vars)+887
#define LINEA_v_fnt_ad C_SYM(linea_vars)+888
#define LINEA_v_fnt_nd C_SYM(linea_vars)+892
#define LINEA_v_fnt_st C_SYM(linea_vars)+894
#define LINEA_v_fnt_wr C_SYM(linea_vars)+896
#define LINEA_V_REZ_HZ C_SYM(linea_vars)+898
#define LINEA_v_off_ad C_SYM(linea_vars)+900
#define LINEA_v_stat_0 C_SYM(linea_vars)+904
#define LINEA_V_REZ_VT C_SYM(linea_vars)+906
#define LINEA_BYTES_LIN C_SYM(linea_vars)+908
#define LINEA_v_planes C_SYM(linea_vars)+910
#define LINEA_v_lin_wr C_SYM(linea_vars)+912
#define LINEA_local_pb C_SYM(linea_vars)+914
#define LINEA_COLBIT0 C_SYM(linea_vars)+934
#define LINEA_COLBIT1 C_SYM(linea_vars)+936
#define LINEA_COLBIT2 C_SYM(linea_vars)+938
#define LINEA_COLBIT3 C_SYM(linea_vars)+940
#define LINEA_LSTLIN C_SYM(linea_vars)+942
#define LINEA_LN_MASK C_SYM(linea_vars)+944
#define LINEA_WRT_MODE C_SYM(linea_vars)+946
#define LINEA_X1 C_SYM(linea_vars)+948
#define LINEA_Y1 C_SYM(linea_vars)+950
#define LINEA_X2 C_SYM(linea_vars)+952
#define LINEA_Y2 C_SYM(linea_vars)+954
#define LINEA_PATPTR C_SYM(linea_vars)+956
#define LINEA_PATMSK C_SYM(linea_vars)+960
#define LINEA_MFILL C_SYM(linea_vars)+962
#define LINEA_CLIP C_SYM(linea_vars)+964
#define LINEA_XMINCL C_SYM(linea_vars)+966
#define LINEA_YMINCL C_SYM(linea_vars)+968
#define LINEA_XMAXCL C_SYM(linea_vars)+970
#define LINEA_YMAXCL C_SYM(linea_vars)+972
#define LINEA_XDDA C_SYM(linea_vars)+974
#define LINEA_DDAINC C_SYM(linea_vars)+976
#define LINEA_SCALDIR C_SYM(linea_vars)+978
#define LINEA_MONO C_SYM(linea_vars)+980
#define LINEA_SOURCEX C_SYM(linea_vars)+982
#define LINEA_SOURCEY C_SYM(linea_vars)+984
#define LINEA_DESTX C_SYM(linea_vars)+986
#define LINEA_DESTY C_SYM(linea_vars)+988
#define LINEA_DELX C_SYM(linea_vars)+990
#define LINEA_DELY C_SYM(linea_vars)+992
#define LINEA_FBASE C_SYM(linea_vars)+994
#define LINEA_FWIDTH C_SYM(linea_vars)+998
#define LINEA_STYLE C_SYM(linea_vars)+1000
#define LINEA_LITEMASK C_SYM(linea_vars)+1002
#define LINEA_SKEWMASK C_SYM(linea_vars)+1004
#define LINEA_WEIGHT C_SYM(linea_vars)+1006
#define LINEA_ROFF C_SYM(linea_vars)+1008
#define LINEA_LOFF C_SYM(linea_vars)+1010
#define LINEA_SCALE C_SYM(linea_vars)+1012
#define LINEA_CHUP C_SYM(linea_vars)+1014
#define LINEA_TEXTFG C_SYM(linea_vars)+1016
#define LINEA_SCRTCHP C_SYM(linea_vars)+1018
#define LINEA_SCRPT2 C_SYM(linea_vars)+1022
#define LINEA_TEXTBG C_SYM(linea_vars)+1024
#define LINEA_COPYTRAN C_SYM(linea_vars)+1026
#define LINEA_FILL_ABORT C_SYM(linea_vars)+1028
