#define LA(val) LINEA_##val
#define LINEA_mouse_cdb _linea_vars+54 
#define LINEA_INQ_TAB _linea_vars+128 
#define LINEA_DEV_TAB _linea_vars+218 
#define LINEA_GCURX _linea_vars+308 
#define LINEA_GCURY _linea_vars+310 
#define LINEA_HIDE_CNT _linea_vars+312 
#define LINEA_MOUSE_BT _linea_vars+314 
#define LINEA_REQ_COL _linea_vars+316 
#define LINEA_SIZ_TAB _linea_vars+412 
#define LINEA_TERM_CH _linea_vars+442 
#define LINEA_chc_mode _linea_vars+444 
#define LINEA_CUR_WORK _linea_vars+446 
#define LINEA_def_font _linea_vars+450 
#define LINEA_font_ring _linea_vars+454 
#define LINEA_font_count _linea_vars+470 
#define LINEA_line_cw _linea_vars+472 
#define LINEA_loc_mode _linea_vars+474 
#define LINEA_num_qc_lines _linea_vars+556 
#define LINEA_str_mode _linea_vars+558 
#define LINEA_val_mode _linea_vars+560 
#define LINEA_cur_ms_stat _linea_vars+562 
#define LINEA_disab_cnt _linea_vars+564 
#define LINEA_newx _linea_vars+566 
#define LINEA_newy _linea_vars+568 
#define LINEA_draw_flag _linea_vars+570 
#define LINEA_mouse_flag _linea_vars+571 
#define LINEA_sav_cur_x _linea_vars+572 
#define LINEA_sav_cur_y _linea_vars+574 
#define LINEA_retsav _linea_vars+576 
#define LINEA_mouse_cursor_save _linea_vars+580 
#define LINEA_tim_addr _linea_vars+844 
#define LINEA_tim_chain _linea_vars+848 
#define LINEA_user_but _linea_vars+852 
#define LINEA_user_cur _linea_vars+856 
#define LINEA_user_mot _linea_vars+860 
#define LINEA_v_cel_ht _linea_vars+864 
#define LINEA_v_cel_mx _linea_vars+866 
#define LINEA_v_cel_my _linea_vars+868 
#define LINEA_v_cel_wr _linea_vars+870 
#define LINEA_v_col_bg _linea_vars+872 
#define LINEA_v_col_fg _linea_vars+874 
#define LINEA_v_cur_ad _linea_vars+876 
#define LINEA_v_cur_of _linea_vars+880 
#define LINEA_v_cur_cx _linea_vars+882 
#define LINEA_v_cur_cy _linea_vars+884 
#define LINEA_v_period _linea_vars+886 
#define LINEA_v_cur_tim _linea_vars+887 
#define LINEA_v_fnt_ad _linea_vars+888 
#define LINEA_v_fnt_nd _linea_vars+892 
#define LINEA_v_fnt_st _linea_vars+894 
#define LINEA_v_fnt_wr _linea_vars+896 
#define LINEA_V_REZ_HZ _linea_vars+898 
#define LINEA_v_off_ad _linea_vars+900 
#define LINEA_v_stat_0 _linea_vars+904 
#define LINEA_V_REZ_VT _linea_vars+906 
#define LINEA_BYTES_LIN _linea_vars+908 
#define LINEA_v_planes _linea_vars+910 
#define LINEA_v_lin_wr _linea_vars+912 
#define LINEA_local_pb _linea_vars+914 
#define LINEA_COLBIT0 _linea_vars+934 
#define LINEA_COLBIT1 _linea_vars+936 
#define LINEA_COLBIT2 _linea_vars+938 
#define LINEA_COLBIT3 _linea_vars+940 
#define LINEA_LSTLIN _linea_vars+942 
#define LINEA_LN_MASK _linea_vars+944 
#define LINEA_WRT_MODE _linea_vars+946 
#define LINEA_X1 _linea_vars+948 
#define LINEA_Y1 _linea_vars+950 
#define LINEA_X2 _linea_vars+952 
#define LINEA_Y2 _linea_vars+954 
#define LINEA_PATPTR _linea_vars+956 
#define LINEA_PATMSK _linea_vars+960 
#define LINEA_MFILL _linea_vars+962 
#define LINEA_CLIP _linea_vars+964 
#define LINEA_XMINCL _linea_vars+966 
#define LINEA_YMINCL _linea_vars+968 
#define LINEA_XMAXCL _linea_vars+970 
#define LINEA_YMAXCL _linea_vars+972 
#define LINEA_XDDA _linea_vars+974 
#define LINEA_DDAINC _linea_vars+976 
#define LINEA_SCALDIR _linea_vars+978 
#define LINEA_MONO _linea_vars+980 
#define LINEA_SOURCEX _linea_vars+982 
#define LINEA_SOURCEY _linea_vars+984 
#define LINEA_DESTX _linea_vars+986 
#define LINEA_DESTY _linea_vars+988 
#define LINEA_DELX _linea_vars+990 
#define LINEA_DELY _linea_vars+992 
#define LINEA_FBASE _linea_vars+994 
#define LINEA_FWIDTH _linea_vars+998 
#define LINEA_STYLE _linea_vars+1000 
#define LINEA_LITEMASK _linea_vars+1002 
#define LINEA_SKEWMASK _linea_vars+1004 
#define LINEA_WEIGHT _linea_vars+1006 
#define LINEA_ROFF _linea_vars+1008 
#define LINEA_LOFF _linea_vars+1010 
#define LINEA_SCALE _linea_vars+1012 
#define LINEA_CHUP _linea_vars+1014 
#define LINEA_TEXTFG _linea_vars+1016 
#define LINEA_SCRTCHP _linea_vars+1018 
#define LINEA_SCRPT2 _linea_vars+1022 
#define LINEA_TEXTBG _linea_vars+1024 
#define LINEA_COPYTRAN _linea_vars+1026 
#define LINEA_FILL_ABORT _linea_vars+1028 
