#define AESPROCESS_a_uda 0 
#define AESPROCESS_a_pd 2440 
#define AESPROCESS_a_cda 2744 
#define AESPROCESS_a_evb 2784 
#define SIZEOF_AESPROCESS 2924 
#define SHELL_sh_doexec 0 
#define SHELL_sh_dodef 2 
#define SHELL_sh_isdef 4 
#define SHELL_sh_isgem 6 
#define SHELL_sh_desk 8 
#define SHELL_sh_cdir 21 
#define SIZEOF_SHELL 136 
#define THEGLO_g_int 0 
#define THEGLO_g_scrap 5848 
#define THEGLO_s_cdir 5962 
#define THEGLO_s_cmd 6076 
#define THEGLO_g_work 6204 
#define THEGLO_g_dta 6332 
#define THEGLO_g_fpdx 6380 
#define THEGLO_g_olist 6636 
#define THEGLO_g_rawstr 7596 
#define THEGLO_g_tmpstr 7677 
#define THEGLO_g_valstr 7758 
#define THEGLO_g_fmtstr 7839 
#define THEGLO_w_win 7920 
#define THEGLO_g_accreg 8400 
#define THEGLO_g_acctitle 8404 
#define THEGLO_g_acc 8428 
#define SIZEOF_THEGLO 8432 
#define UDA_u_insuper 0 
#define UDA_u_regs 4 
#define UDA_u_spsuper 64 
#define UDA_u_spuser 68 
#define UDA_u_oldspsuper 72 
#define UDA_u_super 76 
#define UDA_u_supstk 2436 
#define SIZEOF_UDA 2440 
#define AESPD_p_link 0 
#define AESPD_p_thread 4 
#define AESPD_p_uda 8 
#define AESPD_p_name 12 
#define AESPD_p_cda 20 
#define AESPD_p_ldaddr 24 
#define AESPD_p_pid 28 
#define AESPD_p_stat 30 
#define AESPD_p_unused 32 
#define AESPD_p_evwait 34 
#define AESPD_p_evflg 36 
#define AESPD_p_flags 38 
#define AESPD_p_evlist 40 
#define AESPD_p_qdq 44 
#define AESPD_p_qnq 48 
#define AESPD_p_qaddr 52 
#define AESPD_p_qindex 56 
#define AESPD_p_queue 58 
#define AESPD_p_appdir 186 
#define SIZEOF_AESPD 304 
#define PD_p_lowtpa 0 
#define PD_p_hitpa 4 
#define PD_p_tbase 8 
#define PD_p_tlen 12 
#define PD_p_dbase 16 
#define PD_p_dlen 20 
#define PD_p_bbase 24 
#define PD_p_blen 28 
#define PD_p_xdta 32 
#define PD_p_parent 36 
#define PD_p_flags 40 
#define PD_p_env 44 
#define PD_p_uft 48 
#define PD_p_lddrv 54 
#define PD_p_curdrv 55 
#define PD_p_1fill 56 
#define PD_p_curdir 64 
#define PD_p_2fill 90 
#define PD_p_3fill 96 
#define PD_p_dreg 104 
#define PD_p_areg 108 
#define PD_p_cmdlin 128 
#define SIZEOF_PD 256 
